'use client';

import { useState } from 'react';
import { Download, FileCode, Terminal, X, Check } from 'lucide-react';
import { Command } from '../types/commands';

interface ExportPanelProps {
  selectedCommands: Command[];
  onClearSelection: () => void;
  onClose: () => void;
}

export default function ExportPanel({ 
  selectedCommands, 
  onClearSelection,
  onClose 
}: ExportPanelProps) {
  const [format, setFormat] = useState<'sh' | 'bat' | 'ps1'>('sh');
  const [includeComments, setIncludeComments] = useState(true);
  const [exporting, setExporting] = useState(false);

  const generateScript = (): string => {
    let script = '';
    
    // Header
    if (format === 'sh') {
      script += '#!/bin/bash\n';
      script += '# Generated by The Modder\'s Log\n';
      script += `# Commands: ${selectedCommands.length}\n`;
      script += `# Date: ${new Date().toISOString()}\n\n`;
      script += 'set -e\n\n';
    } else if (format === 'bat') {
      script += '@echo off\n';
      script += 'REM Generated by The Modder\'s Log\n';
      script += `REM Commands: ${selectedCommands.length}\n`;
      script += `REM Date: ${new Date().toISOString()}\n\n`;
    } else if (format === 'ps1') {
      script += '# Generated by The Modder\'s Log\n';
      script += `# Commands: ${selectedCommands.length}\n`;
      script += `# Date: ${new Date().toISOString()}\n\n`;
    }

    selectedCommands.forEach((cmd, index) => {
      if (includeComments) {
        script += `# ${index + 1}. ${cmd.title}\n`;
        script += `# Category: ${cmd.category} | Type: ${cmd.type} | Risk: ${cmd.risk}\n`;
        if (cmd.notes) {
          script += `# Note: ${cmd.notes}\n`;
        }
        script += '#\n';
      }
      
      // Add command
      script += cmd.command;
      script += '\n\n';
    });

    return script;
  };

  const handleExport = () => {
    setExporting(true);
    
    const script = generateScript();
    const blob = new Blob([script], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    
    const a = document.createElement('a');
    a.href = url;
    a.download = `modders-log-script.${format}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    
    URL.revokeObjectURL(url);
    
    setTimeout(() => {
      setExporting(false);
      onClearSelection();
      onClose();
    }, 500);
  };

  const formatLabels = {
    sh: { label: 'Bash (.sh)', desc: 'Linux/macOS/WSL' },
    bat: { label: 'Batch (.bat)', desc: 'Windows CMD' },
    ps1: { label: 'PowerShell (.ps1)', desc: 'Windows PowerShell' }
  };

  if (selectedCommands.length === 0) {
    return (
      <div className="fixed bottom-4 left-4 right-4 md:left-auto md:right-4 md:w-96 bg-[var(--s1)] border border-[var(--b2)] rounded-lg shadow-lg z-40">
        <div className="p-4">
          <div className="flex items-center justify-between mb-2">
            <h3 className="font-display font-bold text-white flex items-center gap-2">
              <FileCode className="w-4 h-4 text-[var(--y)]" />
              Export Script
            </h3>
            <button onClick={onClose} className="text-[var(--t3)] hover:text-[var(--t1)]">
              <X className="w-4 h-4" />
            </button>
          </div>
          <p className="text-sm text-[var(--t2)]">
            Select commands to export as a script file
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="fixed bottom-4 left-4 right-4 md:left-auto md:right-4 md:w-96 bg-[var(--s1)] border border-[var(--b2)] rounded-lg shadow-lg z-40">
      <div className="p-4">
        <div className="flex items-center justify-between mb-4">
          <h3 className="font-display font-bold text-white flex items-center gap-2">
            <FileCode className="w-4 h-4 text-[var(--y)]" />
            Export {selectedCommands.length} Commands
          </h3>
          <button onClick={onClose} className="text-[var(--t3)] hover:text-[var(--t1)]">
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Format Selection */}
        <div className="space-y-2 mb-4">
          <label className="text-xs font-mono text-[var(--t3)] uppercase tracking-wider">
            Script Format
          </label>
          <div className="grid grid-cols-3 gap-2">
            {(Object.keys(formatLabels) as Array<keyof typeof formatLabels>).map((fmt) => (
              <button
                key={fmt}
                onClick={() => setFormat(fmt)}
                className={`p-2 rounded text-xs text-center transition-colors ${
                  format === fmt 
                    ? 'bg-[var(--yd)] text-[var(--y)] border border-[var(--y)]/30' 
                    : 'bg-[var(--s3)] text-[var(--t2)] border border-[var(--b2)] hover:border-[var(--b3)]'
                }`}
              >
                <div className="font-mono font-medium">{formatLabels[fmt].label}</div>
                <div className="text-[10px] text-[var(--t3)] mt-1">{formatLabels[fmt].desc}</div>
              </button>
            ))}
          </div>
        </div>

        {/* Options */}
        <div className="mb-4">
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={includeComments}
              onChange={(e) => setIncludeComments(e.target.checked)}
              className="rounded border-[var(--b2)] bg-[var(--s3)] text-[var(--y)] focus:ring-[var(--y)]"
            />
            <span className="text-sm text-[var(--t2)]">Include command metadata as comments</span>
          </label>
        </div>

        {/* Preview */}
        <div className="mb-4">
          <label className="text-xs font-mono text-[var(--t3)] uppercase tracking-wider block mb-2">
            Preview
          </label>
          <div className="bg-[var(--s2)] rounded p-3 font-mono text-xs text-[var(--t2)] max-h-32 overflow-y-auto">
            <pre>{generateScript().slice(0, 500)}{generateScript().length > 500 ? '...' : ''}</pre>
          </div>
        </div>

        {/* Actions */}
        <div className="flex gap-2">
          <button
            onClick={onClearSelection}
            className="flex-1 py-2 px-4 bg-[var(--s3)] text-[var(--t2)] rounded hover:bg-[var(--s4)] transition-colors text-sm"
          >
            Clear
          </button>
          <button
            onClick={handleExport}
            disabled={exporting}
            className="flex-[2] py-2 px-4 bg-[var(--y)] text-black font-medium rounded hover:opacity-90 transition-opacity text-sm flex items-center justify-center gap-2"
          >
            {exporting ? (
              <>
                <Check className="w-4 h-4" />
                Exported!
              </>
            ) : (
              <>
                <Download className="w-4 h-4" />
                Download .{format}
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}
